version: 2.1
jobs:

  Sketch-Python:
    docker:
      - image: "circleci/python:3.6.4" 
    steps:
      - checkout
      - run: python sketch.py

  Run-Test-Sketch:
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout 
      - run: python test_sketch.py 


  Employee-Python:
    docker:
      - image: "circleci/Python:3.6.4"
    steps:
      - checkout
      - run: python employee.py

  Run-Test-Employee:
    docker: 
      - image: "circleci/Python:3.6.4"

    steps:
      - checkout
      - run: python test_employee.py

  Now-Complete:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Approval Complete
          command: |
            echo 'Do work once the approval has completed'

workflows:
 version: 2
 Example_Workflow:
   jobs:

     - Sketch-Python  
     - Employee-Python 

     - Run-Test-Sketch:
        requires:
          - Sketch-Python

     - Run-Test-Employee:
        requires:
         - Employee-Python

     - Hold-For-Approval:
         type: approval
         requires:
           - Run-Test-Sketch
           - Run-Test-Employee

     - Now-Complete:
         requires:
           - Hold-For-Approval
